name: "Release & Publish to NPM"

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["End-to-End Tests"]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v4 # É bom atualizar para a última versão aqui também, se possível

      - name: Use Node.js ${{ matrix.node-version }}
        # Altere para a versão 4 (ou a mais recente) da ação setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:coverage

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage

      - name: Build
        run: npm run build

      - name: Initialize Git User
        run: |
            git config --global user.email "rorteg@gmail.com"
            git config --global user.name "Release Workflow"

      - name: Initialize the NPM config
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        
      - name: Release and Publish
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
       #run: node ./node_modules/.bin/semantic-release
